export const CHANGE_TEMP_UNIT = "CHANGE_TEMP_UNIT";
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER";
export const GET_WEATHER_DATA_REQUEST = "GET_WEATHER_DATA_REQUEST";
export const GET_WEATHER_DATA_SUCCESS = "GET_WEATHER_DATA_SUCCESS";
export const GET_WEATHER_DATA_FAILURE = "GET_WEATHER_DATA_FAILURE";
